### ISSUE TITLE
[BUG] iPhone 7 writing issues

### ISSUE THREAD

**Issue by Robinb2005** [placiibo/placiibo-bugs#1]
**Describe the bug**
I can’t write the tags on my IPhone 7 Plus. TagInfo can read them, but placiibo can’t write them. After a few seconds it says that it’s done but the NFC isn’t written after that.

**To Reproduce**

1. Go to 'Placiibo' on an IPhone 7 Plus
2. Click on 'Write to tag'
3. Wait till the mark pops up
4. If you try the ntag you see that’s nothing written on it.

**Expected behaviour**
It should be written and working.

**Actual behaviour**
Nothing is written and the ntag doesn’t work.

**Reproducibility :**
It happens everytime.

**iOS version**: 
13.4.1
**iOS device**: 
IPhone 7 Plus
**Jailbroken**: 
No
**placiibo version + build**: 
Version 0.1.0

**Screenshots**
![991F902D-6B8D-4CBF-A354-A2FF2162A3CF](https://user-images.githubusercontent.com/42154161/82127415-9ac89c00-97b3-11ea-9e28-0035726478bf.png)

**Screen recording**
`https://youtu.be/4gabUlW5vxA `

**Relevant files**
I used the key file and amiibo.

**NFC Tag**
![A387465A-586B-41F2-B297-47C657FFF1C7](https://user-images.githubusercontent.com/42154161/82127449-e7ac7280-97b3-11ea-94de-c9db39238f28.png)

**Additional context**
There are more people with this problem.

**Comment by placiibo** [comment]
Could you please fully fill out the bug report template? 

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Actual behaviour**
What actually happened instead

**Reproducibility :** 
How consistent can you reproduce the issue?



**iOS version**:
Version of iOS this bug occurred on (can be found in Settings.app > General)
**iOS device**: 
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: 
Whether or not your device is jailbroken
**placiibo version + build**: 
Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. *Version 0.1.0 (10)* 






**Screenshots**
If possible, add screenshots to help explain your problem.

**Screen recording**
If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**NFC Tag**
If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred. 

**Additional context**
Add any other context about the problem here.

---

Alvast bedankt

**Comment by Robinb2005** [comment]
I updated it

**Comment by Robinb2005** [comment]
> Could you please fully fill out the bug report template?
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behaviour**
> A clear and concise description of what you expected to happen.
> 
> **Actual behaviour**
> What actually happened instead
> 
> **Reproducibility :**
> How consistent can you reproduce the issue?
> 
> **iOS version**:
> Version of iOS this bug occurred on (can be found in Settings.app > General)
> **iOS device**:
> For example iPhone XS, iPhone 7, etc.
> **Jailbroken**:
> Whether or not your device is jailbroken
> **placiibo version + build**:
> Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. _Version 0.1.0 (10)_
> 
> **Screenshots**
> If possible, add screenshots to help explain your problem.
> 
> **Screen recording**
> If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.
> 
> **Relevant files**
> If applicable, add the bin files that you used while the bug occurred
> 
> **NFC Tag**
> If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred.
> 
> **Additional context**
> Add any other context about the problem here.
> 
> Alvast bedankt

It’s updated

**Comment by placiibo** [comment]
Thanks for updating it. Sadly this isn't a bug that is fixable as it's due to h/w design. But I'l at least try to improve UX by improving communication about the state the process is in.

**Comment by Robinb2005** [comment]
> Thanks for updating it. Sadly this isn't a bug that is fixable as it's due to h/w design. But I'l at least try to improve UX by improving communication about the state the process is in.

Thank you

**Comment by heyemuhlee** [comment]
My bad i tried looking to see if this was already reported and couldn’t find it but yes I’m having the same issue with a regular iPhone 7!

**Comment by placiibo** [comment]
To anyone experiencing this issue; consider filling out this survey to help us get a bigger picture on the matter: https://forms.gle/irJRggzjcTKpUGTN7

**Comment by placiibo** [comment]
Closed, I can't find a common element between models that show issues. There are some vague indicators that certain iPhone 7 models have poorer implementation of the NFC antenna, but nothing I can pin down with my limited resources. Earlier reports during iOS 13 beta suggest that there were similar issues with reading tags as opposed ot writing that Apple managed to fix with s/w. Best course of action is to file bug report with Apple.
