### ISSUE TITLE
[Feature] Graphic on NTAG215 placement

### ISSUE THREAD

**Issue by ironandstee1** [placiibo/placiibo-bugs#15]
**Try to describe your suggestion succinctly in the form of a user story**
As a user of coin size NTAG215 stickers, I want a graphic illustration of how to orient the NTAG215 so that it is easier to get started. 

**Is your feature request related to a problem? Please describe.**
It's frustrating when using this app for the first time to tell where the NTAG215 should be placed relative to the phone and this is not made clear from the prompt displayed when write is selected. I ended up spending ~10 minutes the first time looking up where these should be placed and how they should be held and downloading another app to see if they had already been written to. I found that it was best for me to hold them white side to phone, top right near the camera. Just holding them up to the top middle of my phone didn't work. This was on an iPhone 8+. 

**Describe the solution you'd like**
A "how-to" section in the about section with an image showing what it looks like when a tag is actually written and what that looks like on the screen (blue bar on top). 

**Describe alternatives you've considered**
There are plenty of alternatives that are preference based. Adding documentation online, placing documentation elsewhere within the app, making youtube videos, etc etc

**Additional context**
N/A

**Comment by placiibo** [comment]
There are too many factors to be able to provide something useful in this regard. From the phone's internal placement of the NFC antenna and it's quality (looking at you iPhone 7), to if and which case is being used on the phone, to the quality of the NFC tag and (the size of) it's internal antenna, to where the antenna in the tag is located, etc. etc.  

The way it's supposed to work is without actually letting the phone and the tag touch each other, Apple explicity doesn't allow developers to tell users to hold it against the device. Any issues regarding this is to be taken up with Apple or the tag manufacturer. 

Because of the above the prompt that is displayed with it's animation is the best it's going to get.  

On a slightly different, but relevant note: there will be an in app option to confirm if the tag is written/what's written on the tag, but that's still in early pre-alpha for now.
