### ISSUE TITLE
[BUG] Limit is not reset after uninstalling the app

### ISSUE THREAD

**Issue by HQuest** [placiibo/placiibo-bugs#40]
After upgrading to the new Placiibo app, I confirmed the issues I reported were resolved. Thank you for that.

I then decided to play as a regular user, uninstalling the previous version and downloading the new one, but seems library files were left behind from the previous placiibo version (or from TestFlight). The library shows empty but trying to add a new binary file takes me to the purchase page as if I had my two free slots already used.

Deleted the app one more time and reinstalled from the App Store, still a no go. Now I’m stuck with no items on my library and no way to add new ones. Perks of being a beta tester 😂

**Comment by placiibo** [comment]
Thank you for your feedback. 

The limit of two persists regardless of if you delete entries from the library or even completely delete the enitre app. You can add **two** binary files in **total** before being asked to upgrade to placiibo+ . 

This intended behaviour and therefor not a bug.

**Comment by HQuest** [comment]
Hmm, so if I understand it right, I am now unable to use the app unless I cash you a burger, a pizza or a sushi (would be my preference) because I had files from the beta I did not removed before installing the official app and was presented with this “intended behavior”.

Doesn’t look fair to me - but again, “perks” of being a tester.

**Comment by placiibo** [comment]
> Hmm, so if I understand it right, I am now unable to use the app unless I cash you a burger, a pizza or a sushi (would be my preference) because I had files from the beta I did not removed before installing the official app and was presented with this “intended behavior”.
> 
> Doesn’t look fair to me - but again, “perks” of being a tester.
> 
> Edit: See https://hquest.pro.br/placiibo.mp4 for a live view from my device.


There are a couple of scenarios: 

1. Normally a user can add a total of two binary files to the library and make as much NFC tags from those binary files as they want at no charge. Those two are a lifetime limit. 

2. A TestFlight tester has been able to add unlimited amount of binary files to make as much NFC tags from those binary files at no charge.  

3. If a TestFlight tester installs the regular retail version from the AppStore over the TestFlight version they keep whatever they have loaded into the library at no charge. If at this point they are below the limit as mentioned in 1, then 1 applies, if they are above the limit then what they have is what they get. 

The perks of being a tester were that you could use placiibo without limitations *and* could migrate whatever you had in your library free of charge, I'd say that's more than fair since it's more than what non-testers get.  

Even if it leads to some scenarios where you unknowingly and accidentally shoot yourself in the foot by deleting the app and the library with it, I'd say a TF tester got a more extensive free trail than a non-tester, which is still more than fair. 

It's a shame you feel otherwise, but of course you're free to do so.

**Comment by HQuest** [comment]
Oh no, don't get me wrong. I just had not understood, until now, that two is a lifetime limit - I was reading it as "two maximum at a time". I see the rationale of it and I understand odd things are expected to happen in those non-regular cases as I was under, being a beta user. With that in mind, yes, I fully agree this is not a bug but an expected behavior.

Octopus is my favorite - hope you like some ;)
