### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abbiesaunders** [placiibo/placiibo-bugs#42]
So I try to write a tag and it won’t let me I’ve wrote tags before but it won’t let me write Any I’ve deleted and re installed the app 3 times can someone help

**Comment by placiibo** [comment]
Could you file a new bugreport [through here](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md&title=%5BBUG%5D) and fill out the questions asked to the best of your ability?

This current report has a lot of essential information missing, making it hard to determine what the issue is and what's causing it.

**Comment by placiibo** [comment]
Thank you for your feedback. Unfortunately most bugs on iOS 14 are caused by iOS itself so those are beyond our control and require Apple to fix them on their end. 

Despite this, it would be very helpful if you'd file a new bug report [through here](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md&title=%5BBUG%5D) and fill out the questions that are asked, to the best of your ability. 

Thus far now new trends in terms of crashes are visible on our end.
