### ISSUE TITLE
[BUG] iOS 14 issues

### ISSUE THREAD

**Issue by DistortionR** [placiibo/placiibo-bugs#43]
App crashes often and most of the time it will require a full phone restart to be useable again. I understand that ios 14 is still in beta but as it is coming out in a few weeks I thought it would be good to raise the issue now.

**Comment by placiibo** [comment]
Thank you for your feedback. Unfortunately most bugs on iOS 14 are caused by iOS itself so those are beyond our control and require Apple to fix them on their end. 

Despite this, it would be very helpful if you'd file a new bug report [through here](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md&title=%5BBUG%5D) and fill out the questions that are asked, to the best of your ability. 

Thus far now new trends in terms of crashes are visible on our end.
