### ISSUE TITLE
[BUG] the payment didn’t work?

### ISSUE THREAD

**Issue by juanlikespizza** [placiibo/placiibo-bugs#44]
[MY BUG] 

Hi, Placiibo!

I have a Bug where I was buying placiibo+ for about $4.99 and didn’t get it?? Is there a reason why? 
Also they already took my money out. Is it possible if you can give me the subscription?

[SCREENSHOTS] 
![05B92C29-2264-46A9-97BE-6AB212433695](https://user-images.githubusercontent.com/70084718/90971063-ac67c100-e4d1-11ea-88d4-8a733885519b.png)
![92EE613C-2B58-4520-8A69-798F940B3EE9](https://user-images.githubusercontent.com/70084718/90971065-b25da200-e4d1-11ea-9c82-461e87a1042d.png)
 
1st. Photo is about me paying the $4.99 
2nd. Photo is about the app telling me that I can only try 2 times and that’s for the free trial...

Placiibo please solve this Bug, give me back my money or subscription if is possible. 

Thank you very much for the patience. 
Have a wonderful day.

**Comment by juanlikespizza** [comment]
hey, placiibo sorry for the late reply but If i reset my phone will it
delete all my stuff??? thats what i was wondering so i decided to do
nothing instead... and also i dont know how. so please help me placiibo

**Comment by placiibo** [comment]
If you reset your phone it will indeed delete any files you've imported into placiibo and you'll have to import them back. The free trial won't reset so if you've used up the two imports, you'll have to upgrade to placiibo+ to continue using the app. 

Since there was no follow up in the bug report and the issue seem to have resolved based on other reports I'll be closing the bugreport. Thank you for your contributions. Should you need any further assistance, you can use the built in email functionality within the app.
